### ISSUE TITLE
MANO and SMPL Parameters

### ISSUE THREAD

**Issue by CalciferZh** [zhixuany/HUMBI#1]
Thank you so much for releasing the data. It is a wonderful dataset and will definitely help a lot for the community. I just quickly checked the data and got a question regarding to the SMPL and MANO parameters.

For the SMPL model, 86 variables are provided in the sample data for each image. As far as I know, SMPL has 24 joints (therefore 72 variables for pose) and 10 shape parameters, which is not consistent with 86, How should I interpret them?

Similarly, MANO has 16*3 pose parameters and 10 shape parameters, but in the sample data 36 variables were provided.

Thank you again for publishing this great dataset. Looking forward to your reply :)

**Comment by CalciferZh** [comment]
I just checked the supplementary document. SMPL's 86 variables are 24*3 pose + 10 shape + 3 translation + 1 scale, but the order is not specified. I'm still confused about the 36 hand variables.

**Comment by zhixuany** [comment]
Thank you for being interested in our dataset. I have just updated README with more explanation. Basically, for hand it is 1-3 for translation, 4-26 for mano pose params (20 components used), 27-36 for mano shape params. For body it is 1 for scale, 2-4 for translation, 5-76 for smpl pose params, 77-86 for smpl shape params.

**Comment by CalciferZh** [comment]
Okay I see. Thank you again for you reply :)
