### ISSUE TITLE
Bounding box for Hand dataset

### ISSUE THREAD

**Issue by Ishan-Kumar2** [zhixuany/HUMBI#11]
Hi,
The bounding box coordinates given are for the original dimension (1980 x 1080), since the img is cropped also, how can I convert these bounding box coordinates for the (250,250) image that is given?
Thanks!

**Comment by zhixuany** [comment]
Hi, so basically the provided 250x250 image samples are cropped from original image (1920 x 1080) using that bounding box.  This is their relations.

**Comment by zhixuany** [comment]
Sorry, it is cropped using given bounding box from original image and then resized to a unified shape (250, 250), does this make it clear now?
