### ISSUE TITLE
the keypoint annotated quality of the hand data of humbi is not very well.

### ISSUE THREAD

**Issue by aqsc** [zhixuany/HUMBI#13]
we check the keypoint annotated quality of the hand data, the quality is very bad. Some keypoints of images are deviated from the accurate of the position of hand joints. And some images is very blur.  Is there any trick to process the dataset?

**Comment by zhixuany** [comment]
The 3d label are generated based on detections from multiview images, so some may not be good enough.  I am not sure what do you mean by "Is there any trick to process the dataset?".

**Comment by aqsc** [comment]
There are not hands in the images, but it has the annotation results and the quality of the annotation is not very well.

**Comment by zhixuany** [comment]
Yes, we acknowledge that happens.
