### ISSUE TITLE
reconstructed SMPL pose is inconsistent with the image

### ISSUE THREAD

**Issue by GentleDell** [zhixuany/HUMBI#14]
Thank you very much for the wonderful work and for releasing this dataset.

I am able to run the python "hello_smpl_for_humbi.py" script on the [Sample_body](https://humbi-dataset.s3.amazonaws.com/body/Sample_body.zip) data, but the mesh generated by the python script is inconsistent with the images in /subject_1/body/00000017/image (e.g. /image0000032.jpg). E.g. 

The image from the sample data:
![rsz_image0000000](https://user-images.githubusercontent.com/23701665/95754060-c9836980-0ca2-11eb-982f-8ed6f9b593fc.png)

Reconstructed mesh generated by the python scripty:
![rsz_screenshot_from_2020-10-12_15-49-08](https://user-images.githubusercontent.com/23701665/95754119-dc963980-0ca2-11eb-99ad-b8072306c99c.png)

In the image, the left and right palms face each other. However, in the reconstructed mesh, the palms face outside. 

I was wondering whether I use the python script correctly and if you observed this as well.

Below are my configurations:
    SMPL model:  I use the model provided in this repo at HUMBI/body/model/basicModel_neutral_lbs_10_207_0_v1.0.0.pkl.
    SMPL codes:  I use the codes from the SMPL website and I have tried with both ver1.1 and ver1.0 but the above inconsistency still exists.
    Configuration of the "hello_smpl_for_humbi.py":
               dataset_path = './Sample_body';
               subject = 1
               frame = 17
               outmesh_path = './smpl_mesh.obj'
               model_path = './body/model/basicModel_neutral_lbs_10_207_0_v1.0.0.pkl'
 
Thank you very for your time and your help would be much appreciated.
Best

Update:
I try the python script with subject_88 (subject_88/body/00000025/image) and the pose of the reconstructed hands is not consistent with the image too.

**Comment by Xbbei** [comment]
@GentleDell 
Hi,  Recently, I want to use this datasets, but i meet the same problem with you, so did you solve this problem?

Best wishes!

**Comment by GentleDell** [comment]
@Xbbei 

Hello Xbbei,

No, I made the decision not to use this dataset. Because there are many similar cases like this in the dataset. But maybe you can try to simply rotate the poses of the hands.

Best,

**Comment by Xbbei** [comment]
@GentleDell 
Hi, GentleDell,

Thanks for your reply! Can you tell me which datasets you use? 

Thanks
Best wishes!

**Comment by GentleDell** [comment]
Hi,

Depending on the tasks you are going to do, you might be interested in  VIBE, GraphCMR, RotationContinuity, TexturePose, MultiGarmentNetwork. 

I would recommend you read related papers published in recent conferences to see if there are new datasets released/available.

Best,
