### ISSUE TITLE
broken download link

### ISSUE THREAD

**Issue by cow8** [zhixuany/HUMBI#15]
can't register at https://lpartdir-cp305.wordpresstemporal.com/humbi-data.net/04-login-page/

**Comment by JackSyu** [comment]
I also encountered the same problem, can you solve it or directly provide the download link of the dataset?

**Comment by zhixuany** [comment]
Sorry guys it was under construction some time ago and should be good now. If this happens again, please send an email to humbi.data@gmail.com and we will provide download links.
