### ISSUE TITLE
3DDFA model to Surrey model conversion

### ISSUE THREAD

**Issue by zhouhaic** [zhixuany/HUMBI#16]
I notice you transformed 3DDFA model to Surrey in Chapter 4.2, and I want to train my network on 3DDFA and HUMBI dataset. So, can you offer some detail about how to did this? Or whether you have a plan to public related code?

Thanks for your work！

**Comment by Gorokke** [comment]
We heuristically fit the model to another model based on the pre-defined several correspondences (e.g., salient eyes, mouth points) in 3D, and then measure the closest distance in 3D to establish the full correspondences. 

Best,
