### ISSUE TITLE
the dataset register page is unavaliable

### ISSUE THREAD

**Issue by fox16789** [zhixuany/HUMBI#17]
When i register in the [website](http://lpartdir-cp305.wordpresstemporal.com/humbi-data.net/05-new-user-register/) it returns 502 error. Dose the server work？

**Comment by zlou** [comment]
Their website and license are currently under reconstruction. Send an email to humbi.data@gmail.com and then they will send you an link for the dataset. Include the following information in your email:
Name:
Affiliation:
Affiliation email (e.g., .edu, or .ac.):
