### ISSUE TITLE
Documentation request: loading MANO hands and SMPL body model together

### ISSUE THREAD

**Issue by jutanke** [zhixuany/HUMBI#18]
I am trying to load the reconstructed hands together with the SMPL mesh/vertices. While loading the SMPL vertices (red) and pose keypoints (yellow) and projecting into a given camera works fine I have some trouble with the hands.
The hand keypoints and the reconstructed hand mesh (blue: left, green: right) seem to be placed at different position than the mesh: 

![image](https://user-images.githubusercontent.com/831215/103897841-5f892d80-50f4-11eb-9f15-6853701cab60.png)
![image](https://user-images.githubusercontent.com/831215/103897899-70d23a00-50f4-11eb-8195-d8f80212d10e.png)

Applying the rotation and translation provided in ```mano_params_l.txt/mano_params_r.txt``` also does not seem to produce the right results.

![image](https://user-images.githubusercontent.com/831215/103899471-be4fa680-50f6-11eb-90bb-88e5877dc860.png)

The camera calibrations for ```body``` and ```hands``` seem to be identical. 

Could you provide a sample of loading SMPL and MANO in the same coordinate frame?

**Comment by jutanke** [comment]
This has actually been asked already: https://github.com/zhixuany/HUMBI/issues/5

@zhixuany Is there an update wrt jointly tracked body and hands or does the dataset - as of now - still treats body and hands separately?

**Comment by zhixuany** [comment]
We allocate different time sessions to capture body movement and hand gestures separately, in order to highlight each. Thus, we did not process hand in sequence focus on body movement, though we made that particular images in the paper showing body and hand mesh together.
