### ISSUE TITLE
import_cam_params function

### ISSUE THREAD

**Issue by kyungjin-lee** [zhixuany/HUMBI#21]
Hello, thank you for this amazing work!

import_cam_params is referenced multiple times but I can't find the function definition.
Could you please provide the implementations?
Thank you!!

**Comment by zhixuany** [comment]
I suppose you are talking about function ["extractCameraParameters"](https://github.com/zhixuany/HUMBI/blob/master/body/extractCameraParameters.m)? It is inside every folder.
