### ISSUE TITLE
Error in crop image

### ISSUE THREAD

**Issue by www516717402** [zhixuany/HUMBI#4]
Thank you for great project.
There is no hand in  **HUMBI/Hand_381_453/subject_381/hand/00000001/image_croped/left/***.png**.
<img src="https://user-images.githubusercontent.com/30460509/86345430-1ad89180-bc8e-11ea-9b3d-5eae27a5b838.png" width = 30%   align=center />

**Comment by zhixuany** [comment]
Thank you for being interested in HUMBI and point that out, we have marked it and will correct that in next round of refinement.

**Comment by www516717402** [comment]
@zhixuany Will the bug dataset be solved already?

**Comment by www516717402** [comment]
@zhixuany Will the bug dataset be solved already?
